src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/main/java/it/gov/pagopa/group/utils/AuditUtilities.java
src/test/java/it/gov/pagopa/group/util/AuditUtilitiesTest.java

**Description**
The purpose of this PR is to allign performance logs and audit logs for the initiative delete.
**List of changes**
-  Modify performance log and info log
-  Modify audit logs
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

fix: delete performance log and audit log fix

---

postman/idpay-group-e2e.postman_collection.json

**Description**
The purpose of this PR is to update the functional tests to add the newly created delete initiative api call.
**List of changes**
-  Updated functional tests: added "Delete initiative" api call after an initiative creation.
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP 1618 adeguamento test group

---

.github/workflows/anchore.yml
Dockerfile
pom.xml

**Description**
The purpose of this PR is to solve the vulnerabilities from CVE with status high
**List of Changes**
- Update dependency 
- Update Dockerfile
- Update Anchore
**Motivation and Context**
**How Has This Been Tested?**
**Types of changes**
**Checklist:**

feat: Idp 1502 risoluzione CVE idpay group

---

.github/PULL_REQUEST_TEMPLATE.md
helm/values.yaml
pom.xml

* fix helm chart annotation
* add pull request template
* bump pom version

fix: promotion to uat

---

.github/workflows/anchore.yml

chore: fix slack notification condition

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API

feat: IDP-1765 selected API retryable

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

feat: Release dev

---

src/main/java/it/gov/pagopa/group/dto/event/QueueCommandOperationDTO.java
src/main/java/it/gov/pagopa/group/repository/GroupRepository.java
src/main/java/it/gov/pagopa/group/repository/GroupRepositoryExtended.java
src/main/java/it/gov/pagopa/group/repository/GroupRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepository.java
src/main/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepositoryExtended.java
src/main/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/test/java/it/gov/pagopa/group/repository/GroupRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceTest.java

The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified QueueCommandOperationDTO
- Added paged delete method to repository
- Modified JUnit tests

fix: IDP 1816 paged delete

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceTest.java

The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified Method
- Added env values
- Modified JUnit tests

fix: Idp 1816 delete paginata

---

Dockerfile
pom.xml
src/main/resources/application.yml

fix: fix CVE-2023-45853,CVE-2023-44487

---

src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java

fix: added StreamHealthIndicator

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

fix: Release dev

---

src/main/java/it/gov/pagopa/group/connector/notification/NotificationServiceImpl.java
src/main/java/it/gov/pagopa/group/connector/pdv/PdvClientRetryer.java
src/main/java/it/gov/pagopa/group/constants/AbstractCostant.java
src/main/java/it/gov/pagopa/group/service/FileValidationServiceImpl.java
src/main/java/it/gov/pagopa/group/utils/ParallelStreamUtils.java

fix: Sonar branch release dev

---

src/main/java/it/gov/pagopa/group/connector/notification/NotificationServiceImpl.java
src/main/java/it/gov/pagopa/group/connector/pdv/PdvClientRetryer.java
src/main/java/it/gov/pagopa/group/constants/AbstractCostant.java
src/main/java/it/gov/pagopa/group/service/FileValidationServiceImpl.java
src/main/java/it/gov/pagopa/group/utils/ParallelStreamUtils.java

* Sonar Fix
* Sonar Fix - remove unused constructor PdvClientRetryer
* Sonar Fix - remove unused variables PdvClientRetryer
---------

fix: Sonar branch release dev (#94)

---

pom.xml
src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/config/HealthIndicatorLoggerTest.java

- Upgrade version
- Add HealthIndicatorLogger
IDP 1125

fix: [IDP-1125] Log actuator health

---

.github/workflows/anchore.yml
Dockerfile

Fix to resolve CVE -> [IDP-2143](https://pagopa.atlassian.net/browse/IDP-2143)
- fix docker image CVE
- fix error in description extraction when no CVE
[IDP-2143]: https://pagopa.atlassian.net/browse/IDP-2143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: IDP-2143 CVE fix

---

src/main/java/it/gov/pagopa/group/repository/GroupRepository.java
src/main/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepository.java
src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/test/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceTest.java

The purpose of this PR is to fix a bug occurring when a whitelist initiative is sent to revision after being rejected
Task: [IDP-2195](https://pagopa.atlassian.net/browse/IDP-2195)
- modify query to find the correct whitelist file
[IDP-2195]: https://pagopa.atlassian.net/browse/IDP-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2195] fix bug send to revision for a whitelist initiative

---

pom.xml
src/main/java/it/gov/pagopa/group/repository/GroupRepository.java
src/main/java/it/gov/pagopa/group/repository/GroupUserWhitelistRepository.java
src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/test/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceTest.java

Promotion to UAT.
- Task IDP-2195 -> fix bug send to revision an initiative in whitelist [(PR)](https://github.com/pagopa/idpay-group/pull/106)

fix: Promote to UAT

---

Dockerfile
pom.xml

fix: Idp-2196 fix CVE

---

src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java
src/main/java/it/gov/pagopa/group/constants/GroupConstants.java
src/main/java/it/gov/pagopa/group/exception/FileDeleteException.java
src/main/java/it/gov/pagopa/group/exception/FileLoadException.java
src/main/java/it/gov/pagopa/group/exception/FileSaveException.java
src/main/java/it/gov/pagopa/group/exception/FolderInitializeException.java
src/main/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceImpl.java
src/test/java/it/gov/pagopa/group/service/BeneficiaryGroupServiceTest.java

- Removed Suppress Warning
- Added custom exception

fix: IDP 2363 fix bug e code smell sonar group

---

src/main/java/it/gov/pagopa/group/constants/GroupConstants.java
src/main/java/it/gov/pagopa/group/exception/ParallelExecutionException.java
src/main/java/it/gov/pagopa/group/utils/ParallelStreamUtils.java
src/test/java/it/gov/pagopa/group/utils/ParallelStreamUtilsTest.java

fix: [IDP-2363] added new exception code

---

pom.xml

chore: bump pom version

---

specs/asyncapi.yaml

chore: [IDP-2488] asyncapi documentation

---

specs/asyncapi.yaml

chore: [IDP 2488] Async Documentation

---

specs/asyncapi.yaml

- Added asyncapi.yml file with async queue census [PR](https://github.com/pagopa/idpay-group/pull/125)

chore: promote to Uat

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/group/connector/pdv/PdvClientErrorDecoder.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/group/connector/pdv/PdvEncryptRestConnectorTest.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD

chore: Fix cve

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/group/connector/pdv/PdvClientErrorDecoder.java
src/test/java/it/gov/pagopa/group/connector/pdv/PdvEncryptRestConnectorTest.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-group/pull/130)

chore: promote to UAT 

---

helm/values-prod.yaml

- Update config java values on PROD environment  [PR](https://github.com/pagopa/idpay-group/pull/134)

chore: promote to MAIN

---

.github/CODEOWNERS
Dockerfile
pom.xml

* amazoncorretto and applicationinsights version change
* CVE-2024-50379 fix
* Update CODEOWNERS

fix: CVE fix (#144)

---

.devops/code-review-pipelines.yml
pom.xml

chore: [IDP-2676 ]update jdk to 21

---

pom.xml

fix: Revert spring version
